
import './globals.css'

import DefaultLayout from '@/app/components/defaultLayout'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <DefaultLayout>
        <body className={inter.className}>{children}</body>
      </DefaultLayout>
    </html>
  )
}
